---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: retro-board
  name: retro-board-backend
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: retro-board
  name: retro-board-backend

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: retro-board
  name: retro-board-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: retro-board-backend
