---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: retro-board
  labels:
    name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        cputype: amd64
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: ghcr.io/retro-board/backend:dev-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DEVELOPMENT
              value: "false"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-vault-token
                  key: token

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: retro-board
  labels:
    app: backend
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: backend
