---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: retro-board
  labels:
    name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        cputype: amd64
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: containers.home.develbox.info/retro-board/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DEVELOPMENT
              value: "false"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-vault-token
                  key: token
            - name: OWNER_ROLE
              value: "company_owner"
            - name: LEADER_ROLE
              value: "retro_leader"
            - name: USER_ROLE
              value: "retro_user"
            - name: RDS_DB
              value: "retro-board"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: retro-board
  labels:
    app: backend
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: backend
